name: Deploy to Vercel
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql, pgsql
      
      - name: Install PHP dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Copy .env.example to .env
        run: cp .env.example .env
      
      - name: Generate APP_KEY
        run: php artisan key:generate
      
      - name: Build frontend assets
        run: npm run build
      
      - name: Create api directory and copy index.php
        run: |
          mkdir -p api
          echo '<?php require __DIR__ . "/../public/index.php";' > api/index.php
      
      - name: Run tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 5432
          DB_DATABASE: postgres
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan test
      
      - name: Run database migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 5432
          DB_DATABASE: postgres
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate --force
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./

     

        
